// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWM-C0OzwxjvYm0Il5Q3wQhNzQo-hHOC4',
    appId: '1:1002920823462:web:73f9e915dda16d55748267',
    messagingSenderId: '1002920823462',
    projectId: 'rc-software',
    authDomain: 'rc-software.firebaseapp.com',
    storageBucket: 'rc-software.firebasestorage.app',
    measurementId: 'G-FNPTL9PQ6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_XQGa6Ci389TPfXY-q4Gty2iLM726ylI',
    appId: '1:1002920823462:android:6a59c3e90be9153c748267',
    messagingSenderId: '1002920823462',
    projectId: 'rc-software',
    storageBucket: 'rc-software.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEMUVSb5RbVnuRbZBd2H__lRmTv4CmyYY',
    appId: '1:1002920823462:ios:8b710b8bf5db0588748267',
    messagingSenderId: '1002920823462',
    projectId: 'rc-software',
    storageBucket: 'rc-software.firebasestorage.app',
    iosBundleId: 'com.example.rcSoftware',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEMUVSb5RbVnuRbZBd2H__lRmTv4CmyYY',
    appId: '1:1002920823462:ios:8b710b8bf5db0588748267',
    messagingSenderId: '1002920823462',
    projectId: 'rc-software',
    storageBucket: 'rc-software.firebasestorage.app',
    iosBundleId: 'com.example.rcSoftware',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWM-C0OzwxjvYm0Il5Q3wQhNzQo-hHOC4',
    appId: '1:1002920823462:web:2cc37dd46e553151748267',
    messagingSenderId: '1002920823462',
    projectId: 'rc-software',
    authDomain: 'rc-software.firebaseapp.com',
    storageBucket: 'rc-software.firebasestorage.app',
    measurementId: 'G-7TEYWVBXC3',
  );
}
